In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)
b = np.array([[1, 2, 3], [4, 5, 6]], dtype = 'int8')
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
b.shape
a.ndim # gets the dimension of the array

1

In [4]:
b.nbytes # returns the total size of the array ub bytes
b.itemsize # returns the size of each element in bytes
b.size # returns the total number of elements in the array

6

In [5]:
c = np.array([[1,2,3,4,5,6,7,8], [9,10,11,12,13,14,15,16]], dtype= 'int8')
print(c)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [6]:
c[0, :]

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

In [7]:
np.full([3,3],3012)

array([[3012, 3012, 3012],
       [3012, 3012, 3012],
       [3012, 3012, 3012]])

In [8]:
np.random.rand(3,3)
np.random.random_sample(c.shape)

array([[0.51879541, 0.70027711, 0.20358822, 0.38989544, 0.80685803,
        0.01152179, 0.24771378, 0.13460356],
       [0.47495851, 0.77671554, 0.04730075, 0.25542087, 0.13031027,
        0.3011628 , 0.84031409, 0.47001496]])

In [9]:
np.random.randint(100,size=(2,2),dtype='int8')

array([[74, 35],
       [45, 76]], dtype=int8)

In [10]:
a = np.ones((5,5),dtype='int8')
print(a)
z = np.full((3,3),0,dtype='int8')
z[1,1]=9
a[1:4,1:4]=z
a

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [11]:
# x = np.full((int(1e5),int(1e5)),0,dtype='int8')
# for i in range(0,int(1e5)):
#     for k in range(0,int(1e5)):
#         x[i,k]=np.random.randint(1,30)

In [12]:
a = np.random.randint(1,20,size=(3,4),dtype='int8')
b = a.copy()#if i don't use copy the it will be like both a and b will point towards one matrix so any changes made in any one will reflect on both



In [13]:
b[1,3]=30
print(a)
print(b)

[[17  7  8 18]
 [11  9  4  1]
 [15 10  5 18]]
[[17  7  8 18]
 [11  9  4 30]
 [15 10  5 18]]


In [14]:
c = np.random.randint(1,20,size=(15,17))
d = np.random.randint(1,20,size=(17,15))
print(c)
print(d)

[[12  3  8 12  7 16  7  6 18 16  6  4 18  3 14  2  3]
 [14 18 11 14 14 17  2  5 15 17 13 17  4  7 18  7 17]
 [10 13  8  5 10  6  3 19 17 10  4  8 16 17 11 19 13]
 [19 12  1 19  1 15 11 13  1  7  4  2 15  2 19  4 16]
 [11  2  8 10 15 16 17 17  1  4 10 16  2 17  2 11  1]
 [ 3 14 12 16  6  8 17 16  9  6 14  5  1 13 14 13  6]
 [ 8 10 13 16  3  8  5 12  6 16 12  8  6  9  9  2  2]
 [15  1 15  3  5 19 10  2  8 13 19 15  9  4 11 13  7]
 [17 16 14  9  5  3  8 13 17 13  4  9 19  5 16  6 18]
 [13  8  6 11 17 14 11 12 15 15 19  5  6 15 14  1 12]
 [ 7 16  1  8  9 12  8  4 16  5  3 17  2  4  1  5 15]
 [14 18  6 11 12 18 15 18  6 14  8 17 17 14  3  1  7]
 [11 18 17 18  9  6  7 15  2 15 14 19 19  3 18  9 13]
 [ 7 13 15 18  8  3  2 18 14  7  2  4  6  6 10  3  7]
 [ 6 15  9  6 18  4  3  5  3  1 18  3  9  1 11  3  4]]
[[10  8 12 15  5 18 15  2  8 13 13  9  2  4  4]
 [12 17  5 16 10  2 19  1  9  2  6 10 16  3 17]
 [ 7 13 15  3  3  3  8 11 17 10  1 10 18  9 13]
 [ 2  1 12  8 18 17  5 13 16 19  9 19  9 16 1

Linear algebra


In [15]:
e = np.matmul(c,d)
print(e)
np.linalg.det(e)

[[1271 1414 1855 1605 1475 1739 1481 1022 2141 1849  954 1331 1354 1413
  1664]
 [1733 1807 2319 2250 2104 2097 1891 1544 2730 2441 1425 1814 2016 1944
  2388]
 [1694 2072 1810 2017 2112 2045 1936 1345 2634 2322 1144 1559 1938 1708
  1762]
 [1432 1320 1617 1658 1817 1898 1592 1075 1950 1796 1219 1388 1444 1336
  1493]
 [1345 1167 1637 1800 1807 1730 1605 1378 2401 2130 1298 1183 1656 1792
  1817]
 [1589 1488 1669 1738 1734 1668 1558 1503 2270 2125 1191 1582 1846 1686
  1978]
 [1199 1321 1680 1420 1471 1607 1296 1179 1959 1846  972 1481 1464 1504
  1741]
 [1493 1348 1978 1636 1617 1696 1511 1336 2270 1959 1247 1371 1584 1640
  1859]
 [1687 2015 1972 1907 1871 1996 1849 1281 2515 2188 1244 1646 1912 1626
  1879]
 [1607 1602 2017 2041 1915 1948 1765 1529 2552 2462 1302 1709 1867 1938
  2202]
 [ 941 1145 1346 1575 1470 1131 1282  868 1900 1476 1067  965 1275 1194
  1494]
 [1595 1787 2095 2232 2268 2111 2134 1365 2897 2380 1513 1572 2035 2018
  2265]
 [1983 1990 2274 1976 2257 2357 1975 168

np.float64(-5.769551953750862e+35)

In [16]:
print(np.linalg.eigvals(e))
print(np.linalg.diagonal(e))
print(np.linalg.inv(e))

[ 2.53373932e+04  +0.j         -4.83561141e+02  +0.j
  4.12853077e+02  +0.j          1.33514970e+02+260.63408982j
  1.33514970e+02-260.63408982j -3.10367987e+02  +0.j
  1.93160933e+02+123.19562589j  1.93160933e+02-123.19562589j
 -7.72902884e+01+192.72795085j -7.72902884e+01-192.72795085j
 -1.99835457e+02  +0.j          1.16443062e+02  +0.j
 -7.57769197e+01  +0.j          4.69522370e+01  +0.j
 -2.28712978e+01  +0.j        ]
[1271 1807 1810 1658 1807 1668 1296 1336 2515 2462 1067 1572 2296 1340
 1415]
[[ 6.41083908e-03 -5.87082696e-03 -3.34529044e-04  1.49083418e-03
  -4.33839623e-04 -2.84160406e-04 -2.07488033e-03 -2.86581523e-03
  -1.13733013e-03  3.58872780e-03  7.76656278e-03 -6.82948310e-03
   4.65125265e-03 -2.91767494e-03  2.58646492e-03]
 [-4.56417872e-03  6.07197388e-03  1.26757420e-03 -4.30705191e-03
  -5.15418046e-03  2.84496382e-03 -7.28289234e-03  1.68093655e-03
   1.13503454e-03  5.23048519e-03 -9.61553885e-03  8.91338911e-03
   2.93836160e-03 -2.98522390e-03 -7.93241390e-0

In [17]:
f = np.identity(7)
print(f)


[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [18]:
h = np.arange(9).reshape(3,3)
h

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

STATISTICS


In [19]:
stats = np.arange(6,dtype='int8').reshape(2,3)
stats[1,1]=2
stats


array([[0, 1, 2],
       [3, 2, 5]], dtype=int8)

In [20]:
np.min(stats,axis=1)
np.max(stats,axis=1)


array([2, 5], dtype=int8)

REORGANISING ARRAYS

In [21]:
x = np.random.randint(1,50,size=(5,5))
x

array([[ 4,  3, 34, 26, 22],
       [ 4, 43, 16, 19, 19],
       [18, 41, 30, 29, 21],
       [26, 31, 24, 25, 18],
       [38, 28, 21,  4, 21]])

In [22]:
np.reshape(x,(25,1))

array([[ 4],
       [ 3],
       [34],
       [26],
       [22],
       [ 4],
       [43],
       [16],
       [19],
       [19],
       [18],
       [41],
       [30],
       [29],
       [21],
       [26],
       [31],
       [24],
       [25],
       [18],
       [38],
       [28],
       [21],
       [ 4],
       [21]])

In [23]:
y = np.random.randint(1,50,size = 5)
z = np.random.randint(1,190,size = 5)
h= np.hstack((y,z))
h

array([ 22,   1,  30,  49,  20, 100,  50,   2,  36, 111])

In [25]:
j=np.ones((2,3))
k = np.zeros((2,9))
np.hstack((j,k))

array([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
a = np.arange(1,31).reshape(6,5)
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
b = a[0:4,1:].copy()
print(np.linalg.diagonal(b))
print(a)


[ 2  8 14 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
